# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec02c5220203817257db51868d1ddff36423cef769bb5129bd421273c7880c8fa56abdd8372afa0fd9f6b45676b784673a54f57c9a191715009c347321717c6

test:
  secret_key_base: d5b9a55520ae137334d3068e3476537f72a42bdc04f21c86d4615e490c2fff19d853e30c174046b4567bb46583c9308335ac620c525979a09f8e6f21ed7495d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
